package ap.project.network.shared.enums;

public enum MessageType
{
    PLAYER_POSITION,
    USER_PROFILE,
    TEST,
    CONNECTION_CONFIRMED,
    CONNECTION_FAILED,
    PRE_LOBBY_PRESENCE,
    LOBBY_PRESENCE,
    PRE_LOBBY_CONFIRMATION,
    PRE_LOBBY_ERROR,
    USER_CHOICE,
    LOBBY_CREATION_MESSAGE,
    LOBBY_CREATED,
    LOBBY_CREATION_FAILED
}
