package ap.project.model.enums;

public enum GameObjectType
{
    JAZZ_SEEDS("Jazz Seeds", "game_objects/seeds/Jazz_Seeds.png"),
    CARROT_SEEDS("Carrot Seeds", "game_objects/seeds/Carrot_Seeds.png"),
    CAULIFLOWER_SEEDS("Cauliflower Seeds", "game_objects/seeds/Cauliflower_Seeds.png"),
    COFFEE_BEAN("Coffee Bean", "game_objects/beans/Coffee_Bean.png"),
    GARLIC_SEEDS("Garlic Seeds", "game_objects/seeds/Garlic_Seeds.png"),
    BEAN_STARTER("Bean Starter", "game_objects/beans/Bean_Starter.png"),
    KALE_SEEDS("Kale Seeds", "game_objects/seeds/Kale_Seeds.png"),
    PARSNIP_SEEDS("Parsnip Seeds", "game_objects/seeds/Parsnip_Seeds.png"),
    POTATO_SEEDS("Potato Seeds", "game_objects/seeds/Potato_Seeds.png"),
    RHUBARB_SEEDS("Rhubarb Seeds", "game_objects/seeds/Rhubarb_Seeds.png"),
    STRAWBERRY_SEEDS("Strawberry Seeds", "game_objects/seeds/Strawberry_Seeds.png"),
    TULIP_BULB("Tulip Bulb", "game_objects/bulb/Tulip_Bulb.png"),
    RICE_SHOOT("Rice Shoot", "game_objects/Rice_Shoot.png"),
    BLUEBERRY_SEEDS("Blueberry Seeds", "game_objects/seeds/Blueberry_Seeds.png"),
    CORN_SEEDS("Corn Seeds", "game_objects/seeds/Corn_Seeds.png"),
    HOPS_STARTER("Hops Starter", "game_objects/Hops_Starter.png"),
    PEPPER_SEEDS("Pepper Seeds", "game_objects/seeds/Pepper_Seeds.png"),
    MELON_SEEDS("Melon Seeds", "game_objects/seeds/Melon_Seeds.png"),
    POPPY_SEEDS("Poppy Seeds", "game_objects/seeds/Poppy_Seeds.png"),
    RADISH_SEEDS("Radish Seeds", "game_objects/seeds/Radish_Seeds.png"),
    RED_CABBAGE_SEEDS("Red Cabbage Seeds", "game_objects/seeds/Red_Cabbage_Seeds.png"),
    STARFRUIT_SEEDS("Starfruit Seeds", "game_objects/seeds/Starfruit_Seeds.png"),
    SPANGLE_SEEDS("Spangle Seeds", "game_objects/seeds/Spangle_Seeds.png"),
    SUMMER_SQUASH_SEEDS("Summer Squash Seeds", "game_objects/seeds/Summer_Squash_Seeds.png"),
    SUNFLOWER_SEEDS("Sunflower Seeds", "game_objects/seeds/Sunflower_Seeds.png"),
    TOMATO_SEEDS("Tomato Seeds", "game_objects/seeds/Tomato_Seeds.png"),
    WHEAT_SEEDS("Wheat Seeds", "game_objects/seeds/Wheat_Seeds.png"),
    AMARANTH_SEEDS("Amaranth Seeds", "game_objects/seeds/Amaranth_Seeds.png"),
    ARTICHOKE_SEEDS("Artichoke Seeds", "game_objects/seeds/Artichoke_Seeds.png"),
    BEET_SEEDS("Beet Seeds", "game_objects/seeds/Beet_Seeds.png"),
    BOK_CHOY_SEEDS("Bok Choy Seeds", "game_objects/seeds/Bok_Choy_Seeds.png"),
    BROCCOLI_SEEDS("Broccoli Seeds", "game_objects/seeds/Broccoli_Seeds.png"),
    CRANBERRY_SEEDS("Cranberry Seeds", "game_objects/seeds/Cranberry_Seeds.png"),
    EGGPLANT_SEEDS("Eggplant Seeds", "game_objects/seeds/Eggplant_Seeds.png"),
    FAIRY_SEEDS("Fairy Seeds", "game_objects/seeds/Fairy_Seeds.png"),
    GRAPE_STARTER("Grape Starter", "game_objects/Grape_Starter.png"),
    PUMPKIN_SEEDS("Pumpkin Seeds", "game_objects/seeds/Pumpkin_Seeds.png"),
    YAM_SEEDS("Yam Seeds", "game_objects/seeds/Yam_Seeds.png"),
    RARE_SEED("Rare Seed", "game_objects/seeds/Rare_Seed.png"),
    POWERDMELON_SEEDS("Powdermelon Seeds", "game_objects/seeds/Powdermelon_Seeds.png"),
    ANCIENT_SEEDS("Ancient Seeds", "game_objects/seeds/Ancient_Seeds.png"),
    MIXED_SEEDS("Mixed Seeds", "game_objects/seeds/Mixed_Seeds.png"),

    BLUE_JAZZ_CROP("Blue Jazz crop", "game_objects/crops/Blue_Jazz.png"),
    CARROT_CROP("Carrot crop", "game_objects/crops/Carrot.png"),
    CAULIFLOWER_CROP("Cauliflower crop", "game_objects/crops/Cauliflower.png"),
    COFFEE_BEAN_CROP("Coffee Bean crop", "game_objects/beans/Coffee_Bean.png"),
    GARLIC_CROP("Garlic crop", "game_objects/crops/Garlic.png"),
    GREEN_BEAN_CROP("Green Bean corp", "game_objects/crops/Green_Bean.png"),
    KALE_CROP("Kale crop", "game_objects/crops/Kale.png"),
    PARSNIP_CROP("Parsnip corp", "game_objects/crops/Parsnip.png"),
    POTATO_CROP("Potato crop", "game_objects/crops/Potato.png"),
    RHUBARB_CROP("Rhubarb crop", "game_objects/crops/Rhubarb.png"),
    STRAWBERRY_CROP("Strawberry crop", "game_objects/crops/Strawberry.png"),
    TULIP_CROP("Tulip crop", "game_objects/crops/Tulip.png"),
    UNMILLED_RICE_CROP("Unmilled Rice crop", "game_objects/crops/Unmilled_Rice.png"),
    BLUEBERRY_CROP("Blueberry corp", "game_objects/crops/Blueberry.png"),
    CORN_CROP("Corn crop", "game_objects/crops/Corn.png"),
    HOPS_CROP("Hops crop", "game_objects/crops/Hops.png"),
    HOT_PEPPER_CROP("Hot Pepper crop", "game_objects/crops/Hot_Pepper.png"),
    MELON_CROP("Melon crop", "game_objects/crops/Melon.png"),
    POPPY_CROP("Poppy crop", "game_objects/crops/Poppy.png"),
    RADISH_CROP("Radish crop", "game_objects/crops/Radish.png"),
    RED_CABBAGE_CROP("Red Cabbage crop", "game_objects/crops/Red_Cabbage.png"),
    STARFRUIT_CROP("Starfruit crop", "game_objects/crops/Starfruit.png"),
    SUMMER_SPANGLE_CROP("Summer Spangle crop", "game_objects/crops/Summer_Spangle.png"),
    SUMMER_SQUASH_CROP("Summer Squash crop", "game_objects/crops/Summer_Squash.png"),
    SUNFLOWER_CROP("Sunflower crop", "game_objects/crops/Sunflower.png"),
    TOMATO_CROP("Tomato crop", "game_objects/crops/Tomato.png"),
    WHEAT_CROP("Wheat crop", "game_objects/crops/Wheat.png"),
    AMARANTH_CROP("Amaranth crop", "game_objects/crops/Amaranth.png"),
    ARTICHOKE_CROP("Artichoke crop", "game_objects/crops/Artichoke.png"),
    BEET_CROP("Beet crop", "game_objects/crops/Beet.png"),
    BOK_CHOY_CROP("Bok Choy crop", "game_objects/crops/Bok_Choy.png"),
    BROCCOLI_CROP("Broccoli crop", "game_objects/crops/Broccoli.png"),
    CRANBERRIES_CROP("Cranberries crop", "game_objects/crops/Cranberries.png"),
    EGGPLANT_CROP("Eggplant crop", "game_objects/crops/Eggplant.png"),
    FAIRY_ROSE_CROP("Fairy Rose crop", "game_objects/crops/Fairy_Rose.png"),
    GRAPE_CROP("Grape corp", "game_objects/crops/Grape.png"),
    PUMPKIN_CROP("Pumpkin crop", "game_objects/crops/Pumpkin.png"),
    YAM_CROP("Yam crop", "game_objects/crops/Yam.png"),
    SWEET_GEM_BERRY_CROP("Sweet Gem Berry crop", "game_objects/crops/Sweet_Gem_Berry.png"),
    POWDERMELON_CROP("Powdermelon crop", "game_objects/crops/Powdermelon.png"),
    ANCIENT_FRUIT_CROP("Ancient Fruit corp", "game_objects/crops/Ancient_Fruit.png"),

    QUARTZ("Quartz", "game_objects/minerals/Quartz.png"),
    EARTH_CRYSTAL("Earth Crystal", "game_objects/minerals/Earth_Crystal.png"),
    FROZEN_TEAR("Frozen Tear", "game_objects/minerals/Frozen_Tear.png"),
    FIRE_QUARTZ("Fire Quartz", "game_objects/minerals/Fire_Quartz.png"),
    EMERALD("Emerald", "game_objects/minerals/Emerald.png"),
    AQUAMARINE("Aquamarine", "game_objects/minerals/Aquamarine.png"),
    RUBY("Ruby", "game_objects/minerals/Ruby.png"),
    AMETHYST("Amethyst", "game_objects/minerals/Amethyst.png"),
    TOPAZ("Topaz", "game_objects/minerals/Topaz.png"),
    JADE("Jade", "game_objects/minerals/Jade.png"),
    DIAMOND("Diamond", "game_objects/minerals/Diamond.png"),
    PRISMATIC_SHARD("Prismatic Shard", "game_objects/minerals/Prismatic_Shard.png"),
    COPPER("Copper", "game_objects/minerals/Copper_Node.png"), //##
    IRON("Iron", "game_objects/minerals/Iron_Node.png"),
    GOLD("Gold", "game_objects/minerals/Gold_Node.png"),
    IRIDIUM("Iridium", "game_objects/minerals/Iridium_Node.png"),

    COMMON_MUSHROOM_FORAGING_CROP("Common Mushroom", "game_objects/crops/Common_Mushroom.png"),
    DAFFODIL_FORAGING_CROP("Daffodil", "game_objects/crops/Daffodil.png"),
    DANDELION_FORAGING_CROP("Dandelion", "game_objects/crops/Dandelion.png"),
    LEEK_FORAGING_CROP("Leek", "game_objects/crops/Leek.png"),
    MOREL_FORAGING_CROP("Morel", "game_objects/crops/Morel.png"),
    SALMONBERRY_FORAGING_CROP("Salmonberry", "game_objects/crops/Salmonberry.png"),
    SPRING_ONION_FORAGING_CROP("Spring Onion", "game_objects/crops/Spring_Onion.png"),
    WILD_HORSERADISH_FORAGING_CROP("Wild Horseradish", "game_objects/crops/Wild_Horseradish.png"),
    FIDDLEHEAD_FERN_FORAGING_CROP("Fiddlehead Fern", "game_objects/crops/Fiddlehead_Fern.png"),
    GRAPE_FORAGING_CROP("Grape", "game_objects/crops/Grape.png"),
    RED_MUSHROOM_FORAGING_CROP("Red Mushroom", "game_objects/crops/Red_Mushroom.png"),
    SPICE_BERRY_FORAGING_CROP("Spice Berry", "game_objects/crops/Spice_Berry.png"),
    SWEET_PEA_FORAGING_CROP("Sweet Pea", "game_objects/crops/Sweet_Pea.png"),
    BLACKBERRY_FORAGING_CROP("Blackberry", "game_objects/crops/Blueberry.png"),
    CHANTERELLE_FORAGING_CROP("Chanterelle", "game_objects/crops/Chanterelle.png"),
    HAZELNUT_FORAGING_CROP("Hazelnut", "game_objects/crops/Hazelnut.png"),
    PURPLE_MUSHROOM_FORAGING_CROP("Purple Mushroom", "game_objects/crops/Purple_Mushroom.png"),
    WILD_PLUM_FORAGING_CROP("Wild Plum", "game_objects/crops/Wild_Plum.png"),
    CROCUS_FORAGING_CROP("Crocus", "game_objects/crops/Crocus.png"),
    CRYSTAL_FRUIT_FORAGING_CROP("Crystal Fruit", "game_objects/crops/Crystal_Fruit.png"),
    HOLLY_FORAGING_CROP("Holly", "game_objects/crops/Holly.png"),
    SNOW_YAM_FORAGING_CROP("Snow Yam", "game_objects/crops/Snow_Yam.png"),
    WINTER_ROOT_FORAGING_CROP("Winter Root", "game_objects/crops/Winter_Root.png"),

    APRICOT_TREE("Apricot Tree", ""),
    CHERRY_TREE("Cherry Tree", ""),
    BANANA_TREE("Banana Tree", ""),
    MANGO_TREE("Mango Tree", ""),
    ORANGE_TREE("Orange Tree", ""),
    PEACH_TREE("Peach Tree", ""),
    APPLE_TREE("Apple Tree", ""),
    POMEGRANATE_TREE("Pomegranate Tree", ""),
    OAK_TREE("Oak Tree", ""),
    MAPLE_TREE("Maple Tree", ""),
    PINE_TREE("Pine Tree", ""),
    MAHOGANY_TREE("Mahogany Tree", ""),
    MUSHROOM_TREE("Mushroom Tree", ""),
    MYSTIC_TREE("Mystic Tree", ""),
    ACORNS_TREE("Acorns", ""),

    Spring_MIXED_SEED("Spring Mixed Seed", "game_objects/seeds/Spring_Seeds.png"),
    SUMMER_MIXED_SEED("Summer Mixed Seed", "game_objects/seeds/Summer_Seeds.png"),
    FALL_MIXED_SEED("Fall Mixed Seed", "game_objects/seeds/Fall_Seeds.png"),
    WINTER_MIXED_SEED("Winter Mixed Seed", "game_objects/seeds/Winter_Seeds.png"),

    EGG("egg", "game_objects/animal_products/Egg.png"),
    SARDINE("sardine", "game_objects/animal_products/Sardine.png"),
    SALMON("salmon", "game_objects/animal_products/Salmon.png"),
    WHEAT("wheat", "game_objects/crops/Wheat.png"),
    LEEK("leek", "game_objects/crops/Leek.png"),
    DANDELION("dandelion", "game_objects/crops/Dandelion.png"),
    MILK("milk", "game_objects/animal_products/Milk.png"),
    PUMPKIN("pumpkin", "game_objects/crops/Pumpkin.png"),
    WHEAT_FLOWER("wheat flower", "game_objects/crops/Wheat_Flour.png"),
    TOMATO("tomato", "game_objects/crops/Tomato.png"),
    CHEESE("cheese", "game_objects/Artisan_good/Cheese.png"),
    CORN("corn", "game_objects/crops/Corn.png"),
    RICE("rice", "game_objects/crops/Rice.png"),
    FIBER("fiber", "game_objects/seeds/Fiber_Seeds.png"),
    COFFEE("coffee", "game_objects/artisan_good/Coffee.png"),
    SUGAR("sugar", "game_objects/crops/Sugar.png"),
    POTATO("potato", "game_objects/crops/Potato.png"),
    OIL("oil", "game_objects/crops/Oil.png"),
    BLUEBERRY("blueberry", "game_objects/crops/Blueberry.png"),
    MELON("melon", "game_objects/crops/Melon.png"),
    APRICOT("apricot", "game_objects/trees/Apricot.png"),
    CHERRY("cherry", "game_objects/trees/Cherry.png"),
    BANANA("banana", "game_objects/trees/Banana.png"),
    MANGO("mango", "game_objects/trees/Mango.png"),
    ORANGE("orange", "game_objects/trees/Orange.png"),
    PEACH("peach", "game_objects/trees/Peach.png"),
    POMEGRANATE("pomegranate", "game_objects/trees/Pomegranate.png"),
    APPLE("apple", "game_objects/trees/Apple.png"),
    OAK_RESIN("oak resin", "game_objects/trees/Oak_Resin.png"),
    MAPLE_SYRUP("maple syrup", "game_objects/trees/Maple_Syrup.png"),
    PINE_TAR("pine tar", "game_objects/trees/Pine_Tar.png"),
    SAP("sap", "game_objects/trees/Sap.png"),
    COMMON_MUSHROOM("common mushroom", "game_objects/trees/Common_Mushroom.png"),
    MYSTIC_SYRUP("mystic syrup", "game_objects/trees/Mystic_Syrup.png"),
    RED_CABBAGE("red cabbage", "game_objects/crops/Red_Cabbage.png"),
    RADISH("radish", "game_objects/crops/Radish.png"),
    AMARANTH("amaranth", "game_objects/crops/Amaranth.png"),
    KALE("kale", "game_objects/crops/Kale.png"),
    BEET("beet", "game_objects/crops/Beet.png"),
    OMELET("omelet", "game_objects/farming/Omelet.png"),
    PARSNIP("parsnip", "game_objects/crops/Parsnip.png"),
    BREAD("bread", "game_objects/crops/Bread.png"),
    CARROT("carrot", "game_objects/crops/Carrot.png"),
    EGGPLANT("eggplant", "game_objects/crops/Eggplant.png"),
    HASH_BROWN("hash brown", "game_objects/farming/Hashbrowns.png"),
    FLOUNDER("flounder", "game_objects/animal_products/Flounder.png"),
    MIDNIGHT_CARP("midnight carp", "game_objects/animal_products/Midnight_Carp.png"),

    FRIED_EGG("fried egg", "game_objects/farming/Fried_Egg.png"),
    BAKED_FISH("baked fish", "game_objects/recipe/Baked_Fish.png"),
    SALAD("salad", "game_objects/crops/Salad.png"),
    PUMPKIN_PIE("pumpkin pie", "game_objects/crops/Pumpkin_Pie.png"),
    SPAGHETTI("spaghetti", "game_objects/crops/Spaghetti.png"),
    PIZZA("pizza", "game_objects/crops/Pizza.png"),
    TORTILLA("tortilla", "game_objects/crops/Tortilla.png"),
    MAKI_ROLL("maki roll", "game_objects/crops/Maki_Roll.png"),
    TRIPLE_SHOT_ESPRESSO("triple shot espresso", "game_objects/recipe/Triple_Shot_Espresso.png"),
    COOKIE("cookie", "game_objects/recipe/Cookie.png"),
    PANCAKE("pancake", "game_objects/crops/Pancakes.png"),
    FRUIT_SALAD("fruit salad", "game_objects/trees/Fruit_Salad.png"),
    RED_PLATE("red plate", "game_objects/crops/Red_Plate.png"),
    SALMON_DINNER("salmon dinner", "game_objects/crops/Salmon_Dinner.png"),
    VEGETABLE_MEDLEY("vegetable medley", "game_objects/recipe/Vegetable_Medley.png"),
    FARMER_LUNCH("farmer's lunch", "game_objects/farming/Farmer_Lunch.png"),
    SURVIVAL_BURGER("survival burger", "game_objects/crops/Survival_Burger.png"),
    DISH_O_THE_SEA("dish O' the Sea", "game_objects/recipe/Dish_O_The_Sea.png"),
    SEAFORM_PUDDING("seaform pudding", "game_objects/crops/Seafoam_Pudding.png"),
    MINER_TREAT("miner's treat", "game_objects/crops/Miner_Treat.png"),

    COPPER_ORE("copper ore", "game_objects/minerals/Copper_Ore.png"),
    COAL("coal", "game_objects/minerals/Coal.png"),
    IRON_ORE("iron ore", "game_objects/minerals/Iron_Ore.png"),
    GOLD_ORE("gold ore", "game_objects/minerals/Gold_Ore.png"),
    COPPER_BAR("copper bar", "game_objects/minerals/Copper_Bar.png"),
    IRON_BAR("iron bar", "game_objects/minerals/Iron_Bar.png"),
    GOLD_BAR("gold bar", "game_objects/minerals/Gold_Bar.png"),
    IRIDIUM_BAR("iridium bar", "game_objects/minerals/Iridium_Bar.png"),
    WOOD("wood", "game_objects/minerals/Wood.png"),
    STONE("stone", "game_objects/minerals/Stone.png"),
    IRIDIUM_ORE("iridium ore", "game_objects/minerals/Iridium_Ore.png"),
    ACORN("acorn", "game_objects/minerals/Acorn.png"),
    MAPLE_SEED("maple seeds", "game_objects/trees/Maple_Seed.png"),
    PINE_CONE("pine cones", "game_objects/trees/Pine_Cone.png"),
    MAHOGANY_SEED("mahogany seeds", "game_objects/trees/Mahogany_Seed.png"),

    CHERRY_BOMB("cherry bomb", "game_objects/crafting/Cherry_Bomb.png"),
    BOMB("bomb", "game_objects/crafting/Bomb.png"),
    MEGA_BOMB("mega bomb", "game_objects/crafting/Mega_Bomb.png"),
    SPRINKLER("sprinkler", "game_objects/crafting/Sprinkler.png"),
    QUALITY_SPRINKLER("quality sprinkler", "game_objects/crafting/Quality_Sprinkler.png"),
    IRIDIUM_SPRINKLER("iridium sprinkler", "game_objects/crafting/Iridium_Sprinkler.png"),
    CHARCOAL_KLIN("charcoal klin", "game_objects/crafting/Charcoal_Kiln.png"),
    FURNACE("furnace", "game_objects/crafting/Furnace.png"),
    SCARECROW("scarecrow", "game_objects/crafting/Scarecrow.png"),
    DELUXE_SCARECROW("deluxe scarecrow", "game_objects/crafting/Deluxe_Scarecrow.png"),
    BEE_HOUSE("bee house", "game_objects/crafting/Bee_House.png"),
    CHEESE_PRESS("cheese press", "game_objects/crafting/Cheese_Press.png"),
    KEG("keg", "game_objects/crafting/Keg.png"),
    LOOM("loom", "game_objects/crafting/Loom.png"),
    MAYONNAISE_MACHINE("mayonnaise machine", "game_objects/crafting/Mayonnaise_Machine.png"),
    OIL_MAKER("oil maker", "game_objects/crafting/Oil_Maker.png"),
    PRESERVES_JAR("preserves jar", "game_objects/crafting/Preserves_Jar.png"),
    DEHYDRATOR("dehydrator", "game_objects/crafting/Dehydrator.png"),
    FISH_SMOKER("fish smoker", "game_objects/crafting/Fish_Smoker.png"),
    MYSTIC_TREE_SEED("mystic tree seeds", "game_objects/trees/Mystic_Tree_Seed.png"),

    HONEY("honey", "game_objects/artisan_good/Honey.png"),
    GOAT_CHEESE("goat cheese", "game_objects/artisan_good/Goat_Cheese.png"),
    BEER("beer", "game_objects/artisan_good/Beer.png"),
    VINEGAR("vinegar", "game_objects/crops/Vinegar.png"),
    JUICE("juice", "game_objects/artisan_good/Juice.png"),
    MEAD("mead", "game_objects/artisan_good/Mead.png"),
    PALE_ALE("pale ale", "game_objects/artisan_good/Pale_Ale.png"),
    WINE("wine", "game_objects/artisan_good/Wine.png"),
    DRIED_MUSHROOM("dried mushroom", "game_objects/artisan_good/Dried_Mushrooms.png"),
    DRIED_FRUIT("dried fruit", "game_objects/artisan_good/Dried_Fruit.png"),
    RAISIN("raisin", "game_objects/artisan_good/Raisins.png"),
    CLOTH("cloth", "game_objects/artisan_good/Cloth.png"),
    MAYONNAISE("mayonnaise", "game_objects/artisan_good/Mayonnaise.png"),
    DUCK_MAYONNAISE("duck mayonnaise", "game_objects/artisan_good/Duck_Mayonnaise.png"),
    DINOSAUR_MAYONNAISE("dinosaur mayonnaise", "game_objects/artisan_good/Dinosaur_Mayonnaise.png"),
    TRUFFLE_OIL("truffle oil", "game_objects/artisan_good/Truffle_Oil.png"),
    PICKLE("pickle", "game_objects/artisan_good/Pickles.png"),
    JELLY("jelly", "game_objects/artisan_good/Jelly.png"),
    SMOKED_FISH("smoothed fish", "game_objects/animal_products/Smoked_Fish.png"),
    GRAPE("grape", "game_objects/crafting/Grape.png"),
    LARGE_MILK("large milk", "game_objects/animal_products/Large_Milk.png"),
    LARGE_GOAT_MILK("large goat milk", "game_objects/animal_products/Large_Goat_Milk.png"),
    LARGE_EGG("large egg", "game_objects/animal_products/Large_Egg.png"),
    DUCK_EGG("duck egg", "game_objects/animal_products/Duck_Egg.png"),
    DINOSAUR_EGG("dinosaur egg", "game_objects/animal_products/Dinosaur_Egg.png"),
    TRUFFLE("truffle", "game_objects/animal_products/Truffle.png"),
    SUNFLOWER("sunflower", "game_objects/crops/Sunflower.png"),
    FISH("Fish", "game_objects/crafting/Fish.png"),
    FLOWER("Flower", "game_objects/crafting/Tub_o_Flowers.png"),
    HEART("Heart", "game_objects/Heart/HeartIconLarge.png"),

    Apricot_Sapling("apricot sapling", "game_objects/trees/Apple_Sapling.png"),
    Cherry_Sapling("cherry sapling", "game_objects/trees/Cherry_Sapling.png"),
    Banana_Sapling("banana sapling", "game_objects/trees/Banana_Sapling.png"),
    Mango_Sapling("mango sapling", "game_objects/trees/Mango_Sapling.png"),
    Orange_Sapling("orange sapling", "game_objects/trees/Orange_Sapling.png"),
    Peach_Sapling("peach sapling", "game_objects/trees/Peach_Sapling.png"),
    Apple_Sapling("apple sapling", "game_objects/trees/Apple_Sapling.png"),
    Pomegranate_Sapling("pomegranate sapling", "game_objects/trees/Pomegranate_Sapling.png"),
    Acorns("acorns", "game_objects/trees/Acorn.png"),
    Maple_Seeds("maple seeds", "game_objects/trees/Maple_Seed.png"),
    Pine_Cones("pine cones", "game_objects/trees/Pine_Cone.png"),
    Mahogany_Seeds("mahogany seeds", "game_objects/trees/Mahogany_Seed.png"),
    Mushroom_Tree_Seeds("mushroom tree seeds", "game_objects/trees/Mushroom_Tree_Seed.png"),
    Mystic_Tree_Seed("mystic tree seeds", "game_objects/trees/Mystic_Tree_Seed.png"),

    FERTILIZER("fertilizer", "game_objects/Fertilizer/Basic_Fertilizer.png"),
    SPECIAL_FERTILIZER("special fertilizer", "game_objects/Fertilizer/Deluxe_Fertilizer.png"),

    CHERRY_BOMB_RECIPE("Cherry Bomb", "game_objects/crafting/Cherry_Bomb.png"),
    BOMB_RECIPE("Bomb", "game_objects/crafting/Bomb.png"),
    MEGA_BOMB_RECIPE("Mega Bomb", "game_objects/crafting/Mega_Bomb.png"),
    SPRINKLER_RECIPE("Sprinkler", "game_objects/crafting/Sprinkler.png"),
    QUALITY_SPRINKLER_RECIPE("Quality Sprinkler", "game_objects/crafting/Quality_Sprinkler.png"),
    IRIDIUM_SPRINKLER_RECIPE("Iridium Sprinkler", "game_objects/crafting/Iridium_Sprinkler.png"),
    CHARCOAL_KILN_RECIPE("Charcoal Klin", "game_objects/crafting/Charcoal_Kiln.png"),
    FURNACE_RECIPE("Furnace", "game_objects/crafting/Furnace.png"),
    SCARECROW_RECIPE("Scarecrow", "game_objects/crafting/Scarecrow.png"),
    DELUXE_SCARECROW_RECIPE("Deluxe Scarecrow", "game_objects/crafting/Deluxe_Scarecrow.png"),
    BEE_HOUSE_RECIPE("Bee House", "game_objects/crafting/Bee_House.png"),
    CHEESE_PRESS_RECIPE("Cheese Press", "game_objects/crafting/Cheese_Press.png"),
    KEG_RECIPE("Keg", "game_objects/crafting/Keg.png"),
    LOOM_RECIPE("Loom", "game_objects/crafting/Loom.png"),
    MAYONNAISE_MACHINE_RECIPE("Mayonnaise Machine", "game_objects/crafting/Mayonnaise_Machine.png"),
    OIL_MAKER_RECIPE("Oil Maker", "game_objects/crafting/Oil_Maker.png"),
    PRESERVES_JAR_RECIPE("Preserves Jar", "game_objects/crafting/Preserves_Jar.png"),
    DEHYDRATOR_RECIPE("Dehydrator", "game_objects/crafting/Dehydrator.png"),
    GRASS_STARTER_RECIPE("Grass Starter", "game_objects/crafting/Grass_Starter.png"),
    FISH_SMOKER_RECIPE("Fish Smoker", "game_objects/crafting/Fish_Smoker.png"),
    MYSTIC_TREE_SEED_RECIPE("Mystic Tree Seed", "game_objects/trees/Mystic_Tree_Seed.png"),

    WOOL("wool", "game_objects/animal_products/Wool.png"),
    GOLD_COIN("gold coin", "game_objects/crafting/Gold.png"),
    Automating_Iridium_WateringCan("automating iridium watering can", "game_objects/Watering_Can/Iridium_Watering_Can.png"),
    HARD_WOOD("hard wood", "game_objects/crafting/Hardwood.png"),
    SALMON_DINNER_RECIPE("salmon dinner recipe", "game_objects/recipe/Salmon_Dinner.png"),

    BOUQUET("Bouquet", "game_objects/Bouquet.png"),
    WEDDING_RING("Wedding Ring", "game_objects/Ring/Warrior_Ring.png"),

    COPPER_TOOL("copper tool", ""),
    COPPER_TRASH_CAN("copper trash can", "game_objects/Tools/Trash_Can_Copper.png"),
    STEEL_TOOL("steel tool", ""),
    STEEL_TRASH_CAN("steel trash can", "game_objects/Tools/Trash_Can_Steel.png"),
    GOLD_TOOL("gold tool", ""),
    GOLD_TRASH_CAN("gold trash can", "game_objects/Tools/Trash_Can_Gold.png"),
    IRIDIUM_TOOL("Iridium tool", ""),
    IRIDIUM_TRASH_CAN("Iridium trash can", "game_objects/Tools/Trash_Can_Iridium.png"),
    TROUT_SOUP("Trout Soup", "game_objects/recipe/Trout_Soup.png"),
    BAMBOO_POLE("Bamboo Pole", "game_objects/Fishing_Pole/Bamboo_Pole.png"),
    TRAINING_ROD("Training Rod", "game_objects/Fishing_Pole/Training_Rod.png"),
    FIBERGLASS_ROD("Fiberglass Rod", "game_objects/Fishing_Pole/Fiberglass_Rod.png"),
    IRIDIUM_ROD("Iridium Rod", "game_objects/Fishing_Pole/Iridium_Rod.png"),
    JOJA_COLA("Joja Cola", "game_objects/Concessions/Joja_Cola_%28large%29.png"),
    HAY("Hay", "game_objects/Tools/Hay_Hopper.png"),
    MILK_PAIL("Milk Pail", "game_objects/Tools/Milk_Pail.png"),
    SHEARS("Shears", "game_objects/Tools/Shears.png"),
    DELUXE_RETAINING_SOIL("Deluxe Retaining Soil", "game_objects/crafting/Deluxe_Retaining_Soil.png"),
    SPEED_GRO("Speed Gro", "game_objects/crafting/Speed-Gro.png"),
    BASIC_RETAINING_SOIL("Basic Retaining Soil", "game_objects/crafting/Basic_Retaining_Soil.png"),
    QUALITY_RETAINING_SOIL("Quality Retaining Soil", "game_objects/crafting/Quality_Retaining_Soil.png"),
    HASHBROWNS_RECIPE("Hashbrowns Recipe", "game_objects/recipe/Hashbrowns.png"),
    OMELET_RECIPE("Omelet Recipe", "game_objects/recipe/Omelet.png"),
    PANCAKES_RECIPE("Pancakes Recipe", "game_objects/recipe/Pancakes.png"),
    BREAD_RECIPE("Bread Recipe", "game_objects/recipe/Bread.png"),
    TORTILLA_RECIPE("Tortilla Recipe", "game_objects/recipe/Tortilla.png"),
    PIZZA_RECIPE("Pizza Recipe", "game_objects/recipe/Pizza.png"),
    MAKI_ROLL_RECIPE("Maki Roll Recipe", "game_objects/recipe/Maki_Roll.png"),
    TRIPLE_SHOT_ESPRESSO_RECIPE("Triple Shot Espresso Recipe", "game_objects/recipe/Triple_Shot_Espresso.png"),
    COOKIE_RECIPE("Cookie Recipe", "game_objects/recipe/Cookie.png"),
    DUCK_FEATHER("Duck Feather", "game_objects/animal_products/Duck_Feather.png"),
    RABBITS_FOOT("Rabbits Foot", "game_objects/animal_products/Rabbit%27s_Foot.png"),
    GOAT_MILK("Goat Milk", "game_objects/animal_products/Goat_Milk.png"),

    AXE("Axe", "game_objects/Tools/Axe/Axe.png"),
    BackPack("BackPack", "game_objects/Tools/Backpack.png"),
    FISHING_POLE("Fishing Pole", "game_objects/Fishing_Pole/Iridium_Rod.png"),
    HOE("Hoe", "game_objects/Tools/Hoe/Iridium_Hoe.png"),
    PICKAXE("Pickaxe", "game_objects/Tools/Pickaxe/Pickaxe.png"),
    SEYTHE("Seythe", "game_objects/Tools/Scythe.png"),
    SHEAR("Shear", "game_objects/Tools/Shears.png"),
    TRASH_CAN("Trash Can", "game_objects/Tools/Trash_Can_Iridium.png"),
    WATERING_CAN("Watering Can", "game_objects/Watering_Can/Watering_Can.png"),

    ANIMAL_BUILDING("animal building", ""),

    SHAD("Shad", "game_objects/animal_products/Shad.png"),
    BLUE_DISCUS("Blue Discus", "game_objects/animal_products/Blue_Discus.png"),
    SQUID("Squid", "game_objects/animal_products/Squid.png"),
    TUNA("Tuna", "game_objects/animal_products/Tuna.png"),
    PERCH("Perch", "game_objects/animal_products/Perch.png"),
    LIONFISH("Lionfish", "game_objects/animal_products/Lionfish.png"),
    HERRING("Herring", "game_objects/animal_products/Herring.png"),
    GHOSTFISH("Ghostfish", "game_objects/animal_products/Ghostfish.png"),
    TILAPIA("Tilapia", "game_objects/animal_products/Tilapia.png"),
    DORADO("Dorado", "game_objects/animal_products/Dorado.png"),
    LEGEND("Legend", "game_objects/animal_products/Legend.png"),
    GLACIER_FISH("Glacier Fish", "game_objects/animal_products/Glacierfish.png"),
    ANGLER("Angler", "game_objects/animal_products/Angler.png"),
    CRIMSON_FISH("Crimson Fish", "game_objects/animal_products/Crimsonfish.png"),

    CHICKEN("Chicken", "game_objects/Animals/White_Chicken.png"),
    DUCK("Duck", "game_objects/Animals/Duck.png"),
    RABBIT("Rabbit", "game_objects/Animals/Rabbit.png"),
    DINOSAUR("Dinosaur", "game_objects/Animals/Dinosaur.png"),
    COW("Cow", "game_objects/Animals/White_Cow.png"),
    GOAT("Goat", "game_objects/Animals/Goat.png"),
    SHEEP("Sheep", "game_objects/Animals/Sheep.png"),
    PIG("Pig", "game_objects/Animals/Pig.png"),

    BASE_PACK("Base Pack", ""),
    LARGE_PACK("Large Pack", ""),
    DELUXE_PACK("Deluxe Pack", ""),
    ;

    private final String name;
    private final String path;

    GameObjectType(String name, String path)
    {
        this.name = name;
        this.path = path;
    }

    @Override
    public String toString()
    {
        return name;
    }

    public String getPath()
    {
        return path;
    }

    public static GameObjectType getGameObjectType(String name)
    {
        for (GameObjectType gameObjectType : GameObjectType.values())
        {
            if (gameObjectType.toString().equalsIgnoreCase(name))
            {
                return gameObjectType;
            }
        }
        return null;
    }
}
